networks:
  ai_network:
    driver: bridge

services:
  duix-avatar-tts:
    build:
      context: ../index-tts-adapter
      dockerfile: Dockerfile.5090
    image: duix-avatar-tts-indextts-5090:latest
    container_name: duix-avatar-tts
    restart: always
    runtime: nvidia
    working_dir: /code
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=compute,graphics,utility,video,display
      - HF_ENDPOINT=https://hf-mirror.com
      - CUDA_MODULE_LOADING=LAZY  # RTX 50 系列优化
    ports:
      - '18180:8080'
    volumes:
      - d:/duix_avatar_data/voice/data:/code/data
    networks:
      - ai_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: '16g'  # RTX 50 系列建议更大的共享内存
    
  duix-avatar-gen-video:
    image: guiji2025/duix.avatar-5090
    container_name: duix-avatar-gen-video
    restart: always
    runtime: nvidia
    privileged: true
    volumes:
      - d:/duix_avatar_data/face2face:/code/data
    environment:
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    shm_size: '8g'
    ports:
      - '8383:8383'
    command: python /code/app_local.py
    networks:
      - ai_network

